### ISSUE TITLE
Writing an ABNF grammar…

### ISSUE THREAD

**Issue by jakwings** [INISON/inison#10]
I want to start simple. There is no syntax for these elements for now:

* Array of Sections `[[section]]`
* Tags
* Literal/Raw strings
* Multi-line strings

because they are the most difficult to consider. I'll post the grammar here.

**Comment by vagoff** [comment]
I wrote in BNF already

> head = "[" keypath "]" NL | "[[" keypath "]]" NL

**Comment by jakwings** [comment]
I use [ABNF](http://www.ietf.org/rfc/rfc5234.txt) because it can differentiate lower-case and upper-case characters, and the grammar can be more readable. :-P

**Comment by vagoff** [comment]
>  it can differentiate lower-case and upper-case characters,

do you mean https://tools.ietf.org/html/rfc7405 ?

**Comment by vagoff** [comment]
by the way, there is a IEC/ISO standard about EBNF http://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf

**Comment by jakwings** [comment]
No, not RFC 7405. I just use `%x??` to explicit define a string and do not use case-insensitive matching.

**Comment by jakwings** [comment]
#11

**Comment by vagoff** [comment]
I think we are need \r, \f and \b 

e.g, I use them for REDENT, INDENT and DEDENT codes (respectively) in two phase source generation

**Comment by vagoff** [comment]
there is a nice trick for writing one level grammars...

to declutter grammar from space specifications, it is very convenient to group them around symbols and parentheses, e.g.:

      rulelist       =  1*( rule / EOL )

      rule           =  rulename defined-as alternation EOL
                        ; continues if next line starts
                        ;  with white space

      defined-as     =  EQ / EQ_SLASH
                        ; basic rules definition and
                        ;  incremental alternatives

      alternation    =  concatenation *(SLASH concatenation)

      concatenation  =  repetition *(SPACE repetition)

      repetition     =  [repeat] element

      repeat         =  1*DIGIT / (*DIGIT "*" *DIGIT)

      element        =  rulename / group / option /
                        char-val / num-val / prose-val

      group          =  OPEN_PAREN alternation CLOSE_PAREN

      option         =  OPEN_BRACKET alternation CLOSE_BRACKET

      char-val       =  DQUOTE *(%x20-21 / %x23-7E) DQUOTE
                         ; quoted string of SP and VCHAR
                         ; without DQUOTE

      num-val        =  "%" (bin-val / dec-val / hex-val)

      bin-val        =  "b" 1*BIT
                         [ 1*("." 1*BIT) / ("-" 1*BIT) ]
                         ; series of concatenated bit values
                         ; or single ONEOF range

      dec-val        =  "d" 1*DIGIT
                        [ 1*("." 1*DIGIT) / ("-" 1*DIGIT) ]

      hex-val        =  "x" 1*HEXDIG
                        [ 1*("." 1*HEXDIG) / ("-" 1*HEXDIG) ]

      prose-val      =  "<" *(%x20-3D / %x3F-7E) ">"
                         ; bracketed string of SP and VCHAR
                         ;  without angles
                         ; prose description, to be used as
                         ;  last resort

      ; -----------------------------------------------------------------------------------

      EOL            = *c-wsp c-nl

      c-wsp          =  WSP / (c-nl WSP)

      c-nl           =  comment / CRLF
                        ; comment or newline

      comment        =  ";" *(WSP / VCHAR) CRLF

      ; -----------------------------------------------------------------------------------

      rulename       =  ALPHA *(ALPHA / DIGIT / "-")

      ; -----------------------------------------------------------------------------------

      SPACE       = 1*c-wsp
      SLASH       = *c-wsp "/" *c-wsp
      EQ          = *c-wsp "=" *c-wsp
      EQ_SLASH    = *c-wsp  "=/" *c-wsp
      OPEN_PAREN  = "(" *c-wsp
      CLOSE_PAREN = *c-wsp ")"
      OPEN_BRACKET  = "[" *c-wsp
      CLOSE_BRACKET = *c-wsp "]"

compare with original version from the rfc:

      rulelist       =  1*( rule / (*c-wsp c-nl) )

      rule           =  rulename defined-as elements c-nl
                         ; continues if next line starts
                         ;  with white space

      rulename       =  ALPHA *(ALPHA / DIGIT / "-")

      defined-as     =  *c-wsp ("=" / "=/") *c-wsp
                         ; basic rules definition and
                         ;  incremental alternatives

      elements       =  alternation *c-wsp

      c-wsp          =  WSP / (c-nl WSP)

      c-nl           =  comment / CRLF
                         ; comment or newline

      comment        =  ";" *(WSP / VCHAR) CRLF

      alternation    =  concatenation
                        *(*c-wsp "/" *c-wsp concatenation)

      concatenation  =  repetition *(1*c-wsp repetition)

      repetition     =  [repeat] element

      repeat         =  1*DIGIT / (*DIGIT "*" *DIGIT)

      element        =  rulename / group / option /
                        char-val / num-val / prose-val

      group          =  "(" *c-wsp alternation *c-wsp ")"

      option         =  "[" *c-wsp alternation *c-wsp "]"

      char-val       =  DQUOTE *(%x20-21 / %x23-7E) DQUOTE
                         ; quoted string of SP and VCHAR
                         ;  without DQUOTE

      num-val        =  "%" (bin-val / dec-val / hex-val)

      bin-val        =  "b" 1*BIT
                         [ 1*("." 1*BIT) / ("-" 1*BIT) ]
                         ; series of concatenated bit values
                         ;  or single ONEOF range

      dec-val        =  "d" 1*DIGIT
                        [ 1*("." 1*DIGIT) / ("-" 1*DIGIT) ]

      hex-val        =  "x" 1*HEXDIG
                        [ 1*("." 1*HEXDIG) / ("-" 1*HEXDIG) ]

      prose-val      =  "<" *(%x20-3D / %x3F-7E) ">"
                         ; bracketed string of SP and VCHAR
                         ;  without angles
                         ; prose description, to be used as
                         ;  last resort

      ALPHA          =  %x41-5A / %x61-7A   ; A-Z / a-z

      BIT            =  "0" / "1"

      CHAR           =  %x01-7F
                         ; any 7-bit US-ASCII character,
                         ;  excluding NUL

      CR             =  %x0D
                          ; carriage return

      CRLF           =  CR LF
                         ; Internet standard newline

      CTL            =  %x00-1F / %x7F
                         ; controls

      DIGIT          =  %x30-39
                         ; 0-9

      DQUOTE         =  %x22
                         ; " (Double Quote)

      HEXDIG         =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

      HTAB           =  %x09
                         ; horizontal tab

      LF             =  %x0A
                         ; linefeed

      LWSP           =  *(WSP / CRLF WSP)
                         ; Use of this linear-white-space rule
                         ;  permits lines containing only white
                         ;  space that are no longer legal in
                         ;  mail headers and have caused
                         ;  interoperability problems in other
                         ;  contexts.
                         ; Do not use when defining mail
                         ;  headers and use with caution in
                         ;  other contexts.

      OCTET          =  %x00-FF
                         ; 8 bits of data

      SP             =  %x20

      VCHAR          =  %x21-7E
                         ; visible (printing) characters

      WSP            =  SP / HTAB
                         ; white space

**Comment by vagoff** [comment]
And also I don't see the point in using %xXX-s for punctuation instead of "xx"-s

**Comment by vagoff** [comment]
do you target some restricted ABNF subset?

**Comment by vagoff** [comment]
Do you plan to use tools like http://www.quut.com/abnfgen/ ?
I wrote same thing for my own, by the way. But it is not polished enough to be released while already used in production.

**Comment by ghost** [comment]
My grammar is not optimized for parsers but humans. So I named almost everything and tell the hex code of punctuation.

Section title and array have different environments for `[` and `]`. That trick does not work well. In fact spaces are not used much in the grammar.

REDENT, INDENT and DEDENT? in configuration files?

I mistype a symbol for the definition of "Sign", so abnfgen doesn't parse it successfully. See #13

**Comment by vagoff** [comment]
> REDENT, INDENT and DEDENT? in configuration files?

e.g.,

```
[generator]
prologue = "#include <stdlib.h>\rint main(int argc, char** argv) {\f"
epilogue = "\nreturn 0;\b}\n"
```

**Comment by vagoff** [comment]
Will generate:

```
#include <stdlib.h>

int main(int argc, char** argv) {
    ...
    return 0;
}
```

**Comment by vagoff** [comment]
> My grammar is not optimized for parsers but humans.

As for me, "[" is more readable than OpenBracket

**Comment by vagoff** [comment]
> Section title and array have different environments for [ and ]. That trick does not work well. In fact spaces are not used much in the grammar.

There are no need to replace EVERY punctuation with space included counterpart. Only when it is convenient.

before:

```
= Key *Space KeyValueSeparator *Space Value
  [ *VSpace Value *( *VSpace Comma *VSpace Value ) ]  ; Optional comma-separated values
  [ *VSpace Comma ]                                   ; Allow one trailing comma
  *VSpace RightBracket                                ; End with ]
  *VSpace RightBrace                                        ; End with }
  *Space Key *( *Space Dot *Space Key )  ; Keys separated by "."
  *Space RightBracket                    ; End with ]
```

after:

```
; ---- "syntactic" section ----
= Key KEY-VALUE-SEPARATOR Value
[ *VSpace Value *( COMMA Value ) ]  ; Optional comma-separated values
[ COMMA ]                                   ; Allow one trailing comma
RIGHT-BRACKET                                ; End with ]
RIGHT-BRACE                                        ; End with }
*Space Key *( DOT Key )  ; Keys separated by "."
RIGHT-BRACKET                    ; End with ]

; ------ "lexical" section -------
KEY-VALUE-SEPARATOR = *Space KeyValueSeparator *Space
COMMA = *VSpace "," *VSpace
RIGHT-BRACKET = *VSpace "]"
RIGHT-BRACE = *VSpace RightBrace
DOT = *Space "." *Space
```

**Comment by vagoff** [comment]
Then, almost all *Space occurances are on "lexical" side, therefore improved readability.

**Comment by ghost** [comment]
Interesting `\f - forward, \b - backward, \r rewind`. Then keep them with `\n \t`.

> As for me, "[" is more readable than OpenBracket

Ok, I just want to show the hex code for everything. I'm willing to change it anytime.

> … Then, almost all *Space occurances are on "lexical" side, therefore improved readability.

No, it is painful to imagine the hidden magic space around the symbol. When I see `COMMA` I tend to believe it is just a comma, and do not want to check the definition again and again to know it is not surrounded by `*Space` but `*VSpace`.

**Comment by ghost** [comment]
If there is just one kind of space, it is fine to address it outside the grammar rules. (not suitable for inison)

**Comment by vagoff** [comment]
> No, it is painful to imagine the hidden magic space around the symbol. When I see COMMA I tend to believe it is just a comma, and do not want to check the definition again and again to know it is not surrounded by *Space but *VSpace.

Well, I got used to multistage grammars, where lexing/preprocessing/parsing stages are separated into several grammars, while you got used to single stage, where everything mentioned in one file (up to spaces).

So we both have different expectations and diametrally different readability hurdles.

**Comment by vagoff** [comment]
So my proposition is boiling down to superficially emulate two stage grammars by dividing actually one stage grammar into several sections; maybe this is deeply flawed, I don't know.

**Comment by vagoff** [comment]
What irritates me next is error prone-ness of situation when spaces of different kinds manually scattered over here and there.

**Comment by ghost** [comment]
The reason of why there are `Space, VSpace, ESpace` is just that I put new lines, comments and semicolons into them. They are just used in these rules now: Expressions, Array, Dict, SectionTitle, <ins>KeyValue</ins>.

If I just want to emphasize the tokens except the ignorable ones, I won't write it in ABNF, nor will I use that trick. You can just erase all `*XSpace` and reach the same readability you want. I don't see it a big problem here.
